# Generated by Django 2.1.4 on 2018-12-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20181216_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
    ]
