# Generated by Django 2.1.4 on 2018-12-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20181216_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='sessions',
            field=models.IntegerField(default=0),
        ),
    ]
