# Generated by Django 2.1.4 on 2018-12-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapysession',
            name='status',
            field=models.CharField(choices=[('Progress', 'progress'), ('Complete', 'complete')], default='Progress', max_length=10),
        ),
    ]
